version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: assetops-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: assetops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v25.1.2
    container_name: assetops-redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - "1G"
      - --reserve-memory
      - "0M"
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
      - "9644:9644"

  telemetry-api:
    build:
      context: .
      dockerfile: apps/telemetry-api/Dockerfile
    container_name: assetops-telemetry-api
    depends_on:
      - postgres
      - redpanda
    env_file:
      - apps/telemetry-api/.env.docker
    ports:
      - "3333:3333"

  query-api:
    build:
      context: .
      dockerfile: apps/query-api/Dockerfile
    container_name: assetops-query-api
    depends_on:
      - postgres
    env_file:
      - apps/query-api/.env.docker
    ports:
      - "3334:3334"

  alert-worker:
    build:
      context: .
      dockerfile: apps/alert-worker/Dockerfile
    container_name: assetops-alert-worker
    depends_on:
      - postgres
      - redpanda
    env_file:
      - apps/alert-worker/.env.docker

volumes:
  postgres_data:
